### ISSUE TITLE
Qualitative Research II

### ISSUE THREAD

**Issue by joelowj** [GIC-CAPSTONE-18/Capstone-Data-Source#2]
After the previous meeting, I believed that you guys are now more familiar with data-related work. 

Task for next meeting:
1. Read up on Convolutional Neural Network,
2. Research and Identify what features constitute a region to be affluent,
3. Get some statistics on real estates and infrastructure pricing for a developed and developing country. 

With regards to using pricing data, I spend some time thinking about it and we could use the pricing data to identify region of higher affluent, and capture the images for training. Since we already determined during training that this image belongs to an affluence region, we can ignore the question of what are the features for an affluent region and let the neural network will pick up this features on its own. This approach might make your job easier, do think about it.

If any of you are still not familiar, please read a few more Deep Learning / Machine Learning papers on images. Or you can approach any of the people in the Deep Learning Team for help.

**Comment by Felicity-jt** [comment]
Summary from 29/09/2017 meeting

1. DS team agreed on selecting landscape features instead of using price as indicators to identify affluent regions. The main reason is the RE websites in India (99acres) are not reliable enough. The prices posted in the RE websites may not be the real transaction prices, but rather the posted prices from sellers, hence they are misleading and not representative enough as an indicator. 

2. Hence we decided on 16 features according to urban planning resources, data available, distinguishing characteristics of each feature (eg. stadium is very distinguishing) and would use them to train the model. Each feature will be attached with a weight and the calculated score measures the affluence level of a region. The weight could be negative as well.

16 features are listed below:
        1. Industrial
	2. Airport
	3. Carpark
	4. High-density residential areas 1 (non-overlapping)
	5. High-density residential areas 2 (overlapping roofs)
	6. Medium-density residential areas
	7. Low-density residential areas
	8. Slums
	9. Greenery
	10. Cricket ground (green)
	11. Cricket ground (brown)
	12. Construction
	13. Cemetery 
	14. Agriculture
	15. Swimming pool/ golf field/ etc
        16. Schools (field)

Each one of us will source data for 4 features. The data must be in a standardized form (i.e. 256*256 pixels). All images should be occupied mainly by a dominant feature, and data from the same feature should very much look the same. For simplicity, data can be sourced from the available datasets online or google maps, they do not have to be within India for now.

**Comment by joelowj** [comment]
@jiawen456 @JwayCube @Felicity-jt @leeyn7 Good work. I will close this issue. If there is anything we need in the future, we can reference to this issue.
